### ISSUE TITLE
In light mode, the code color under View sample dataset is white and the display is not clear.

### ISSUE THREAD

**Issue by llds66** [graphieros/vue-data-ui-doc#4]
![image](https://github.com/user-attachments/assets/150e8bf6-1351-4829-ae38-6b42e0bedcfa)
![image](https://github.com/user-attachments/assets/e6e60344-8ed1-4efc-999c-9e4fcf49f13a)

**Comment by graphieros** [comment]
@llds66 thank you :) Fixed
